services:
  app:
    env_file:
      - .env
      - .env.dev
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - umap-network
